// AUTO-GENERATED from src/lib/avatarIcons.ts. Do not edit by hand.
// Regenerate with: node gen-icon-imports.mjs (from repo root)
import type { Icon } from "@tabler/icons-react";
import {
  IconFlag2,
  IconTrophy,
  IconCrown,
  IconStar,
  IconTarget,
  IconShield,
  IconMedal,
  IconBolt,
  IconDiamond,
  IconRocket,
  IconFlame,
  IconSword,
  IconSwords,
  IconAxe,
  IconChessKing,
  IconChessQueen,
  IconChessKnight,
  IconBallFootball,
  IconBallAmericanFootball,
  IconBallBaseball,
  IconBallBasketball,
  IconBallVolleyball,
  IconBallTennis,
  IconBallBowling,
  IconBike,
  IconRun,
  IconBarbell,
  IconDumbbell,
  IconKarate,
  IconHorseToy,
  IconSailboat,
  IconCompass,
  IconMountain,
  IconWaveSine,
  IconSun,
  IconSunrise,
  IconSunset,
  IconMoon,
  IconSnowflake,
  IconCloud,
  IconCloudRain,
  IconCloudStorm,
  IconCloudFog,
  IconTornado,
  IconVolcano,
  IconTree,
  IconTrees,
  IconLeaf,
  IconLeaf2,
  IconLeafMaple,
  IconPlant,
  IconPlant2,
  IconFlower,
  IconMushroom,
  IconAnchor,
  IconFish,
  IconFeather,
  IconEgg,
  IconDroplet,
  IconCampfire,
  IconWind,
  IconRainbow,
  IconStars,
  IconComet,
  IconGhost,
  IconAlien,
  IconRobot,
  IconRobotFace,
  IconSkull,
  IconMask,
  IconMoodSmile,
  IconMoodHappy,
  IconMoodCrazyHappy,
  IconMoodTongue,
  IconMoodSurprised,
  IconMoodSad,
  IconMoodWink,
  IconMoodKid,
  IconSunglasses,
  IconChefHat,
  IconMoustache,
  IconEyeOff,
  IconBrain,
  IconHandRock,
  IconHandTwoFingers,
  IconThumbUp,
  IconThumbDown,
  IconToiletPaper,
  IconBeer,
  IconGlassCocktail,
  IconPizza,
  IconBurger,
  IconCake,
  IconIceCream,
  IconCandy,
  IconConfetti,
} from "@tabler/icons-react";

export const AVATAR_ICON_COMPONENTS: Record<string, Icon> = {
  "flag-2": IconFlag2,
  "trophy": IconTrophy,
  "crown": IconCrown,
  "star": IconStar,
  "target": IconTarget,
  "shield": IconShield,
  "medal": IconMedal,
  "bolt": IconBolt,
  "diamond": IconDiamond,
  "rocket": IconRocket,
  "flame": IconFlame,
  "sword": IconSword,
  "swords": IconSwords,
  "axe": IconAxe,
  "chess-king": IconChessKing,
  "chess-queen": IconChessQueen,
  "chess-knight": IconChessKnight,
  "ball-football": IconBallFootball,
  "ball-american-football": IconBallAmericanFootball,
  "ball-baseball": IconBallBaseball,
  "ball-basketball": IconBallBasketball,
  "ball-volleyball": IconBallVolleyball,
  "ball-tennis": IconBallTennis,
  "ball-bowling": IconBallBowling,
  "bike": IconBike,
  "run": IconRun,
  "barbell": IconBarbell,
  "dumbbell": IconDumbbell,
  "karate": IconKarate,
  "horse-toy": IconHorseToy,
  "sailboat": IconSailboat,
  "compass": IconCompass,
  "mountain": IconMountain,
  "wave-sine": IconWaveSine,
  "sun": IconSun,
  "sunrise": IconSunrise,
  "sunset": IconSunset,
  "moon": IconMoon,
  "snowflake": IconSnowflake,
  "cloud": IconCloud,
  "cloud-rain": IconCloudRain,
  "cloud-storm": IconCloudStorm,
  "cloud-fog": IconCloudFog,
  "tornado": IconTornado,
  "volcano": IconVolcano,
  "tree": IconTree,
  "trees": IconTrees,
  "leaf": IconLeaf,
  "leaf2": IconLeaf2,
  "leaf-maple": IconLeafMaple,
  "plant": IconPlant,
  "plant2": IconPlant2,
  "flower": IconFlower,
  "mushroom": IconMushroom,
  "anchor": IconAnchor,
  "fish": IconFish,
  "feather": IconFeather,
  "egg": IconEgg,
  "droplet": IconDroplet,
  "campfire": IconCampfire,
  "wind": IconWind,
  "rainbow": IconRainbow,
  "stars": IconStars,
  "comet": IconComet,
  "ghost": IconGhost,
  "alien": IconAlien,
  "robot": IconRobot,
  "robot-face": IconRobotFace,
  "skull": IconSkull,
  "mask": IconMask,
  "mood-smile": IconMoodSmile,
  "mood-happy": IconMoodHappy,
  "mood-crazy-happy": IconMoodCrazyHappy,
  "mood-tongue": IconMoodTongue,
  "mood-surprised": IconMoodSurprised,
  "mood-sad": IconMoodSad,
  "mood-wink": IconMoodWink,
  "mood-kid": IconMoodKid,
  "sunglasses": IconSunglasses,
  "chef-hat": IconChefHat,
  "moustache": IconMoustache,
  "eye-off": IconEyeOff,
  "brain": IconBrain,
  "hand-rock": IconHandRock,
  "hand-two-fingers": IconHandTwoFingers,
  "thumb-up": IconThumbUp,
  "thumb-down": IconThumbDown,
  "toilet-paper": IconToiletPaper,
  "beer": IconBeer,
  "glass-cocktail": IconGlassCocktail,
  "pizza": IconPizza,
  "burger": IconBurger,
  "cake": IconCake,
  "ice-cream": IconIceCream,
  "candy": IconCandy,
  "confetti": IconConfetti,
};
