-- Seed catalog_ideas with 20 curated golf trip destinations
-- Source: slowcountrylife/src/lib/ai-trip-seeds.ts
-- Run manually: psql $DATABASE_URL -f supabase/seed_catalog.sql

INSERT INTO catalog_ideas
  (id, title, location, description, image_url, cost_tier,
   categories, group_types, trip_length, region,
   golf_courses, activities, accommodation, tips, sort_order)
VALUES
  (
    'cat-myrtle-beach',
    'Myrtle Beach Golf Blitz',
    'Myrtle Beach, SC',
    'The Grand Strand offers over 100 courses packed into a short coastal strip — perfect for a value-packed group trip. Oceanfront condos and beach houses keep lodging affordable, and the laid-back atmosphere makes for great post-round evenings.',
    'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=800&q=80',
    '$$',
    ARRAY['golf', 'beach'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['TPC Myrtle Beach', 'Caledonia Golf & Fish Club', 'True Blue Golf Club', 'Barefoot Resort (Love Course)', 'Pawleys Plantation'],
    ARRAY['Golf', 'Beach', 'Seafood dinners', 'Boardwalk nightlife', 'Go-karts', 'Mini golf'],
    'A large oceanfront vacation house or two side-by-side condos split 16 ways lands well under $80/head/night in shoulder season. Check VRBO for beach house rentals along Shore Drive.',
    'Spring (March–May) and fall (September–October) are the sweet spots — cooler temps and lower prices. Avoid summer heat and holiday weeks. Tee times Tuesday–Thursday are cheapest.',
    1
  ),
  (
    'cat-hilton-head',
    'Hilton Head Island Classic',
    'Hilton Head Island, SC',
    'Sea-island golf charm — moss-draped oaks lining fairways, lagoons at every turn, and Atlantic breezes cooling afternoon rounds. Multiple golf communities with villa rentals make group logistics easy.',
    'https://images.unsplash.com/photo-1572721513573-82b8fe9a189b?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf', 'beach'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Harbour Town Golf Links (RBC Heritage)', 'Palmetto Dunes (Arthur Hills)', 'Hilton Head National', 'Port Royal Golf Club', 'Oldfield Club (guest access)'],
    ARRAY['Golf', 'Beach cycling', 'Kayaking', 'Harbour Town lighthouse', 'Lowcountry seafood', 'Pickleball'],
    'Villa and condo rentals in Palmetto Dunes or Sea Pines resort communities. A 4-5BR villa for 8 runs $400–600/night; two of these split 16 ways is very manageable.',
    'Book tee times at Harbour Town months in advance — it fills up. April Heritage week drives prices up dramatically; target late October for value.',
    2
  ),
  (
    'cat-pinehurst',
    'Pinehurst Pilgrimage',
    'Pinehurst, NC',
    'The cradle of American golf — a village built around the game with nine resort courses, including the legendary No. 2, host of multiple US Opens. The Carolina sandhills landscape creates natural beauty unlike anywhere else on the East Coast.',
    'https://images.unsplash.com/photo-1640907526554-a617a1a8645c?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Pinehurst No. 2 (US Open host)', 'Pinehurst No. 4', 'Pinehurst No. 8 (Tom Fazio)', 'Mid Pines Golf Club', 'Pine Needles Lodge & Golf Club'],
    ARRAY['Golf', 'Village walking', 'Historic tours', 'Spa at Pinehurst Resort', 'Croquet', 'Tennis'],
    'The Pinehurst Resort is the classic choice but pricey at rack rates. For groups, vacation rentals in the Village of Pinehurst or nearby Southern Pines offer more room at better value.',
    'No. 2 tee times book months out — plan well ahead. A "package" through the resort for 3–4 courses can save money vs. booking individually. October is peak value season.',
    3
  ),
  (
    'cat-bandon-dunes',
    'Bandon Dunes Bucket List',
    'Bandon, OR',
    'The great American links pilgrimage. Six courses perched on the rugged Oregon coast with Pacific views from virtually every hole. Walking-only, caddies encouraged, and a golf-first culture that strips away everything except the game itself.',
    'https://images.unsplash.com/photo-1766288020088-4b95f5409376?auto=format&fit=crop&w=800&q=80',
    '$$$$',
    ARRAY['golf'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'northwest',
    ARRAY['Bandon Dunes (Mike Keiser, 1999)', 'Pacific Dunes (Tom Doak, ranked top 10 world)', 'Bandon Trails (Coore & Crenshaw)', 'Old Macdonald (Doak replica)', 'Sheep Ranch (cliffside, par 3s)'],
    ARRAY['Golf', 'Caddie rounds', 'Whiskey bar at the lodge', 'Bandon Trails hiking', 'Pool & sauna', 'Card games'],
    'Lodge rooms, houses, and cottages on property. Rates include breakfast and dinner, which helps offset sticker shock. Group houses sleep 4–8 and are worth the upgrade.',
    'Budget $350–500+/round per person including caddie and forecaddie. The lodge''s meal plan is genuinely good. Book 6–12 months out. Fly into North Bend (OTH) or Coos Bay.',
    4
  ),
  (
    'cat-scottsdale',
    'Scottsdale Desert Golf Escape',
    'Scottsdale, AZ',
    'Desert golf at its finest — saguaro cacti framing every shot, mountain backdrops, and 300+ days of sunshine. The nightlife is legendary, the restaurants are excellent, and rental houses with pools are perfect for a crew wanting equal parts golf and hanging out.',
    'https://images.unsplash.com/photo-1743268089111-669fc11da1c7?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf', 'adventure'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southwest',
    ARRAY['TPC Scottsdale (Stadium Course)', 'We-Ko-Pa Golf Club (Saguaro)', 'Troon North (Monument Course)', 'Grayhawk Golf Club (Raptor)', 'Talking Stick Golf Club (O''odham)'],
    ARRAY['Golf', 'Pool time', 'Old Town Scottsdale', 'Desert hiking (Camelback)', 'Spa', 'Spring Training baseball (March)'],
    'Luxury rental homes with pools in Paradise Valley or North Scottsdale split well for groups. Expect $600–1,200/night for a 6–8BR home. AirBnB has solid inventory.',
    'Avoid summer (it''s genuinely dangerous hot). Prime season is January–April; October–November is the sweet spot for value + weather.',
    5
  ),
  (
    'cat-kiawah',
    'Kiawah Island Ocean Course',
    'Kiawah Island, SC',
    'One of the most dramatic venues in American golf — 10 holes directly alongside the Atlantic, brutal winds, and a layout that hosted the Ryder Cup and multiple PGA Championships. Not cheap, but the combination of world-class golf, pristine beach, and wildlife-rich barrier island makes it genuinely special.',
    'https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=80',
    '$$$$',
    ARRAY['golf', 'beach'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['The Ocean Course (Ryder Cup, PGA Championship host)', 'Osprey Point Golf Club', 'Turtle Point Golf Club', 'Cougar Point Golf Club', 'Oak Point Golf Club (Seabrook Island)'],
    ARRAY['Golf', 'Beach', 'Biking island trails', 'Kayaking marshes', 'Night crabbing', 'Luxury resort dining'],
    'Villa rentals within the Kiawah Island Golf Resort or private home rentals on the island. Expect premium prices — this is a premium destination. Off-season (January–February) offers meaningful savings.',
    'The Ocean Course tee time waitlist is real — book the moment your dates are set. The resort''s golf packages can bundle multiple courses at a discount.',
    6
  ),
  (
    'cat-amelia-island',
    'Amelia Island Getaway',
    'Amelia Island, FL',
    'A Florida barrier island with a real small-town feel, excellent golf, and none of the crowded tourist traps. The Ritz-Carlton courses are top-tier, and the Fernandina Beach historic district is charming. Florida weather makes this a great winter escape.',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf', 'beach'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Omni Amelia Island (Long Point Club)', 'Amelia Island Club (Long Point)', 'The Golf Club of Amelia Island', 'Fernandina Beach Golf Course (budget round)', 'Osprey Cove Golf Club (St. Marys, GA)'],
    ARRAY['Golf', 'Beach', 'Fernandina Beach dining', 'Kayaking/paddleboarding', 'Fort Clinch State Park', 'Shrimping boat tours'],
    'The Omni or Ritz-Carlton properties work great for groups. Alternatively, VRBO beach houses on the north end of the island offer more space and kitchen access for ~$600–900/night.',
    'November–March is peak season for Florida golf weather. Summer is hot and humid but slow at the courses — rates drop significantly.',
    7
  ),
  (
    'cat-gulf-shores',
    'Gulf Shores Beach & Golf',
    'Gulf Shores, AL',
    'Alabama''s Gulf Coast is chronically underrated — sugar-white sand, warm emerald water, and affordable golf in a relaxed setting. Beach houses are reasonably priced, and you get Florida-quality beach at a fraction of the price.',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    '$$',
    ARRAY['golf', 'beach'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Craft Farms Golf Resort (Cotton Creek)', 'Peninsula Golf & Racquet Club', 'Kiva Dunes Golf Club', 'Colonial Golf & Tennis Club', 'Gulf Shores Golf Club (budget option)'],
    ARRAY['Golf', 'White sand beach', 'Deep sea fishing', 'ATV beach rides', 'Fresh Gulf seafood', 'Shelling'],
    'Large VRBO/Airbnb beach houses on West Beach or Fort Morgan Peninsula. A 6–8BR house sleeping 16 runs $600–1,000/night — split that and it''s very affordable.',
    'Spring break (March) brings crowds; aim for May or September–October for ideal conditions. Hurricane season runs June–November.',
    8
  ),
  (
    'cat-williamsburg',
    'Williamsburg Colonial Golf',
    'Williamsburg, VA',
    'A legitimately great golf destination that often flies under the radar. Golden Horseshoe''s Green Course is a top-100 American course, and Colonial Williamsburg provides cultural context that most pure golf destinations lack.',
    'https://images.unsplash.com/photo-1639350059346-6dbe5a612c86?auto=format&fit=crop&w=800&q=80',
    '$$',
    ARRAY['golf'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Golden Horseshoe Golf Club (Green Course)', 'Golden Horseshoe Golf Club (Gold Course)', 'Williamsburg National Golf Club', 'Ford''s Colony Country Club', 'Kingsmill Resort (River Course)'],
    ARRAY['Golf', 'Colonial Williamsburg historic tours', 'Jamestown & Yorktown battlefield visits', 'Busch Gardens (optional)', 'Virginia wine tastings', 'Craft brewery scene'],
    'Colonial Williamsburg Foundation has inn and vacation home properties. Alternatively, VRBO homes in the area run more affordable.',
    'April–May and September–October are ideal. The Golden Horseshoe Green Course is THE must-play — Robert Trent Jones Sr. at his best.',
    9
  ),
  (
    'cat-sea-island',
    'Sea Island Luxury Retreat',
    'Sea Island, GA',
    'Where golf groups come when they want to feel pampered. The Cloister hotel is legendary, the Seaside and Plantation courses are world-class, and the service is impeccably Southern. The Presidents Cup has been played here.',
    'https://images.unsplash.com/photo-1693947270655-4efc8368e89f?auto=format&fit=crop&w=800&q=80',
    '$$$$',
    ARRAY['golf', 'beach'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Sea Island Golf Club (Seaside Course — Presidents Cup)', 'Sea Island Golf Club (Plantation Course)', 'Sea Island Golf Club (Retreat Course)', 'Jekyll Island Golf Club (30 min, budget round)'],
    ARRAY['Golf', 'Spa at The Cloister', 'Beach Club', 'Horseback riding', 'Fishing', 'Skeet shooting', 'Tennis'],
    'The Cloister or Sea Island Lodge on-property. These are premium rates ($600–900+/night per room) but include access to all resort amenities.',
    'Call the resort directly about group rates — they have specific group coordinator staff. March/April and October are peak golf weather.',
    10
  ),
  (
    'cat-palm-springs',
    'Palm Springs Desert Classic',
    'Palm Springs, CA',
    'Over 100 golf courses in a compact desert bowl surrounded by the San Jacinto Mountains. January through March is PGA Tour season here, the weather is consistently perfect at 75°F, and the pool house rental scene makes big groups easy.',
    'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf', 'adventure'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southwest',
    ARRAY['PGA West (Stadium Course)', 'La Quinta Country Club', 'Desert Willow Golf Resort (Firecliff)', 'Tahquitz Creek Golf Course (budget round)', 'Mission Hills Country Club (Dinah Shore)'],
    ARRAY['Golf', 'Pool lounging', 'Joshua Tree National Park (day trip)', 'Palm Canyon Drive shopping', 'Aerial tram', 'Casino at Agua Caliente'],
    'Large vacation homes with pools are everywhere in Palm Springs and Rancho Mirage. A 6–8BR home with a private pool runs $700–1,500/night — split 16 ways and it''s exceptional value.',
    'January–March is peak season but worth it. Summer is brutally hot (115°F+) — avoid completely.',
    11
  ),
  (
    'cat-virginia-beach',
    'Virginia Beach Golf Week',
    'Virginia Beach, VA',
    'A solid value-play golf destination with enough courses for a week-long trip, Atlantic Ocean beach access, and a livelier boardwalk scene. Links-style maritime layouts mixed with traditional wooded Virginia courses.',
    'https://images.unsplash.com/photo-1573510459738-7ea3373bcc82?auto=format&fit=crop&w=800&q=80',
    '$$',
    ARRAY['golf', 'beach'],
    ARRAY['guys_trip', 'any'],
    'week_plus',
    'southeast',
    ARRAY['Signature at West Neck Golf Club', 'The Heron Ridge Golf Club', 'Hell''s Point Golf Club (Pete Dye)', 'Cypress Point Country Club', 'Sewells Point Golf Course'],
    ARRAY['Golf', 'Virginia Beach Oceanfront boardwalk', 'Chesapeake Bay fishing', 'Norfolk Naval Base tours', 'Craft beer scene', 'Kayaking'],
    'Large oceanfront rentals in Virginia Beach run $1,000–2,000/week for a big house — dramatically cheaper than South Carolina equivalents.',
    'Late September through October has ideal weather and the summer crowds are gone. The Atlantic seabreeze makes afternoon rounds pleasant even in summer.',
    12
  ),
  (
    'cat-branson',
    'Ozarks Golf Adventure',
    'Branson, MO',
    'Branson gets overlooked but shouldn''t be. Ozark Mountain topography creates dramatic elevation changes, green fees are often under $60, and the rental cabin scene means a massive group lodge for what you''d pay for two hotel rooms elsewhere.',
    'https://images.unsplash.com/photo-1542224566-6e85f2e6772f?auto=format&fit=crop&w=800&q=80',
    '$',
    ARRAY['golf', 'adventure'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'midwest',
    ARRAY['Branson Creek Golf Club (Tom Fazio)', 'Top of the Rock Golf Course (Jack Nicklaus)', 'Thousand Hills Golf Club', 'Holiday Hills Golf Course', 'Pointe Royale Golf Course'],
    ARRAY['Golf', 'Table Rock Lake boating', 'Branson shows & entertainment', 'Zip lining', 'Fishing', 'Silver Dollar City theme park'],
    'Large vacation lodges and cabins around Table Rock Lake sleep 16–20 easily at $400–800/night total. This is where Branson truly shines for group travel — the value is unmatched.',
    'May–June and September–October are the sweet spots. Top of the Rock is a unique experience but pricey. Green fees at most courses are a fraction of resort destinations.',
    13
  ),
  (
    'cat-punta-cana',
    'Punta Cana All-Inclusive',
    'Punta Cana, Dominican Republic',
    'All-inclusive Caribbean golf done right — Teeth of the Dog at Casa de Campo is a bucket-list Caribbean course with the sea lapping at seven holes. Add in unlimited food and drinks, and this trip runs itself.',
    'https://images.unsplash.com/photo-1678816331175-a61a6835e889?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf', 'beach', 'international'],
    ARRAY['guys_trip', 'couples', 'any'],
    'week_plus',
    'international',
    ARRAY['Teeth of the Dog at Casa de Campo (top 10 Caribbean)', 'Dye Fore at Casa de Campo (canyon/sea views)', 'La Estancia Golf Course', 'Barceló Bávaro Golf Course'],
    ARRAY['Golf', 'All-inclusive beach resort', 'Snorkeling & diving', 'ATV excursions', 'Deep sea fishing', 'Catamaran party cruise', 'Casino'],
    'All-inclusive resorts (Hard Rock, Barcelo, Iberostar) run $200–350/person/night all-in, including food, drinks, and resort activities.',
    'Book the Teeth of the Dog tee time the moment you can — it sells out. Factor in golf fees separately from the AI resort rate. December–April is ideal weather.',
    14
  ),
  (
    'cat-cabo',
    'Cabo Golf & Beaches',
    'Cabo San Lucas, Mexico',
    'That rare combination of legitimate world-class golf with spectacular desert-meets-ocean scenery and a lively resort town. Jack Nicklaus-designed courses overlook the Sea of Cortez, and the exchange rate makes dining and activities significantly cheaper.',
    'https://images.unsplash.com/photo-1580020663348-79fdfe831847?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf', 'beach', 'international'],
    ARRAY['guys_trip', 'couples', 'any'],
    'week_plus',
    'international',
    ARRAY['Cabo del Sol (Desert Course — Jack Nicklaus)', 'Cabo del Sol (Ocean Course)', 'Diamante Dunes Course (David McLay Kidd)', 'Querencia Golf Club', 'Club Campestre San Jose del Cabo'],
    ARRAY['Golf', 'Beach club scene', 'Snorkeling at Cabo Pulmo', 'Deep sea fishing (marlin!)', 'ATV desert tours', 'Whale watching (Dec–Mar)'],
    'All-inclusive resorts (Pueblo Bonito, Grand Velas) or villa rentals in Pedregal/Quivira. VRBO luxury villas with infinity pools sleep 10–16 and can be surprisingly affordable split many ways.',
    'October–May is the window — summer is too hot and humid. Diamante Dunes is the most dramatic course on the Baja Peninsula. Direct flights from most US hubs to SJD.',
    15
  ),
  (
    'cat-ireland',
    'Ireland Links Tour',
    'County Clare & Kerry, Ireland',
    'Playing links golf in Ireland is a transformative experience — ancient landscapes, winds that change direction every hour, and a golf culture that revolves around the 19th hole. Lahinch, Ballybunion, and Old Head are among the greatest links courses on the planet.',
    'https://images.unsplash.com/photo-1571243827682-305f9c83051b?auto=format&fit=crop&w=800&q=80',
    '$$$$',
    ARRAY['golf', 'international'],
    ARRAY['guys_trip', 'any'],
    'week_plus',
    'international',
    ARRAY['Lahinch Golf Club (Old Course — top 50 world)', 'Ballybunion Golf Club (Old Course)', 'Old Head Golf Links (cliffside drama)', 'Doonbeg Golf Club (Greg Norman)', 'Tralee Golf Club (Arnold Palmer)'],
    ARRAY['Links golf', 'Traditional pub sessions', 'Cliffs of Moher', 'Dingle Peninsula drive', 'Whiskey distillery tours', 'Castles', 'Fishing villages'],
    'Farmhouse B&Bs and village guesthouses provide authentic Irish character at €100–150/night. Larger houses in the countryside sleep 10–16 for group rentals.',
    'June–August is warmest but also busiest. May and September offer fewer crowds. Bring serious rain gear — Irish links weather is part of the experience.',
    16
  ),
  (
    'cat-st-andrews',
    'St. Andrews Pilgrimage',
    'St. Andrews, Scotland',
    'The home of golf. Walking the 18th fairway of the Old Course with the R&A Clubhouse behind you is a moment every golfer should experience. Scotland''s other treasures (Carnoustie, Kingsbarns) are all within an hour.',
    'https://images.unsplash.com/photo-1657369957695-d13476038898?auto=format&fit=crop&w=800&q=80',
    '$$$$',
    ARRAY['golf', 'international'],
    ARRAY['guys_trip', 'any'],
    'week_plus',
    'international',
    ARRAY['Old Course at St. Andrews (must apply for ballot)', 'Kingsbarns Golf Links (Fife coast)', 'Carnoustie Golf Links (Championship Course)', 'Dumbarnie Links (modern links masterpiece)', 'St. Andrews Castle Course'],
    ARRAY['Golf', 'St. Andrews old town walking', 'Whisky tasting', 'Edinburgh day trip', 'Kilt shopping', 'Scottish pub culture'],
    'The Old Course Hotel is iconic but pricey. Self-catering houses and holiday flats in St. Andrews town sleep groups well at £150–300/night total. Book 12+ months ahead.',
    'The Old Course ballot system is real — apply online up to 2 days before. Late June has the longest daylight (can play until 10pm). Caddies are mandatory on Old Course.',
    17
  ),
  (
    'cat-whistling-straits',
    'Whistling Straits & The American Club',
    'Kohler, WI',
    'Hosted the 2021 Ryder Cup and looks like it was airlifted straight from the Irish coast — 2.5 miles of Lake Michigan shoreline. The Kohler resort experience (American Club hotel) is five-star all the way.',
    'https://images.unsplash.com/photo-1635328800844-0e68e80ab258?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'midwest',
    ARRAY['Whistling Straits (Straits Course — Ryder Cup)', 'Whistling Straits (Irish Course)', 'Blackwolf Run (River Course)', 'Blackwolf Run (Meadow Valleys)'],
    ARRAY['Golf', 'American Club luxury resort', 'Kohler Waters Spa', 'Road America racetrack', 'Lake Michigan shoreline', 'Sheboygan bratwurst scene'],
    'The American Club is the premier option — a Forbes 5-star hotel in a converted workers'' village. Inn on Woodlake is a more affordable Kohler property.',
    'Late summer (August–September) is ideal — Wisconsin weather is beautiful and crowds are manageable. Tee times at Whistling Straits book out far in advance.',
    18
  ),
  (
    'cat-streamsong',
    'Streamsong Hidden Gem',
    'Bowling Green, FL',
    'A legitimately world-class golf resort in the middle of nowhere — built on reclaimed phosphate mining land that created stunning sandy ridges and wetland scenery. Three courses (Blue, Red, Black), all excellent. No beach, no distractions — just golf and each other.',
    'https://images.unsplash.com/photo-1639350059252-4cfd60e3249b?auto=format&fit=crop&w=800&q=80',
    '$$$',
    ARRAY['golf'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Streamsong Blue (Coore & Crenshaw)', 'Streamsong Red (Coore & Crenshaw)', 'Streamsong Black (Gil Hanse — links-style)'],
    ARRAY['Golf', 'Resort pool & spa', 'Fishing in the lakes', 'Card tournaments', 'Cocktail competitions', 'Bird watching (herons, osprey)'],
    'On-resort lodge rooms and cottages. This is a true destination resort — staying on property is the experience. Group rates available for 10+ people.',
    'October–April is peak season. The golf is walking-friendly and the pace is unhurried. This works as a 3-day trip (one course per day). Fly into Tampa (1.5 hrs) or Orlando (1.5 hrs).',
    19
  ),
  (
    'cat-sandhills',
    'Sandhills Budget Run',
    'Southern Pines, NC',
    'The NC Sandhills give you Pinehurst-adjacent quality at a fraction of the resort prices. Tobacco Road is one of the most uniquely designed courses in America — 80-foot elevation changes on land that looks like golf''s version of the moon.',
    'https://images.unsplash.com/photo-1640907526554-a617a1a8645c?auto=format&fit=crop&w=800&q=80',
    '$$',
    ARRAY['golf'],
    ARRAY['guys_trip', 'any'],
    '4_days',
    'southeast',
    ARRAY['Tobacco Road Golf Club (Mike Strantz design)', 'Mid Pines Inn & Golf Club (Donald Ross)', 'Pine Needles Lodge & Golf Club (Donald Ross)', 'Talamore Golf Club', 'Longleaf Golf & Family Club (budget round)'],
    ARRAY['Golf', 'Village of Pinehurst walking', 'Brewery scene (Southern Pines Brewing)', 'Aberdeen historic district', 'Driving range competition', 'Card games at the house'],
    'Large vacation homes in Aberdeen, Pinehurst, or Southern Pines. VRBO has good inventory of 5–8BR homes at $400–700/night.',
    'Tobacco Road is the must-play — book it first. Green fees at non-Pinehurst-resort courses run $60–120, making this a great value week.',
    20
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  location = EXCLUDED.location,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  cost_tier = EXCLUDED.cost_tier,
  categories = EXCLUDED.categories,
  group_types = EXCLUDED.group_types,
  trip_length = EXCLUDED.trip_length,
  region = EXCLUDED.region,
  golf_courses = EXCLUDED.golf_courses,
  activities = EXCLUDED.activities,
  accommodation = EXCLUDED.accommodation,
  tips = EXCLUDED.tips,
  sort_order = EXCLUDED.sort_order;
