import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { router, authedProcedure } from "../trpc";
import { requireTripMember, requireTripRole } from "../middleware";

const logisticsType = z.enum(["lodging", "transport", "general"]);

export const logisticsRouter = router({
  // -----------------------------------------------------------------------
  // list — any member can view logistics items
  // -----------------------------------------------------------------------
  list: authedProcedure
    .input(z.object({ tripId: z.string() }))
    .use(requireTripMember)
    .query(async ({ ctx }) => {
      // `select("*")` is intentional here: logistics_items is a narrow table
      // (~22 columns) and the lodging/transport UI consumes essentially all of
      // them — title, link, sleeps, address, check_in/out_date, check_in/out_time,
      // transport_type, pickup_location/time, is_confirmed, total_price, notes,
      // and the image_url/image_urls cover photos. An explicit column list would
      // enumerate nearly the whole table for no payload saving while risking a
      // silent break whenever a new column is added and the list isn't updated.
      const { data, error } = await ctx.supabase
        .from("logistics_items")
        .select("*")
        .eq("trip_id", ctx.tripId)
        .order("sort_order", { ascending: true })
        .order("created_at", { ascending: true });

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to fetch logistics items",
        });
      }

      return data ?? [];
    }),

  // -----------------------------------------------------------------------
  // create — Organizer+ can add logistics items (RLS INSERT RETURNING split)
  // -----------------------------------------------------------------------
  create: authedProcedure
    .input(
      z.object({
        tripId: z.string(),
        type: logisticsType,
        title: z.string().min(1).max(200),
        link: z.string().max(1000).optional(),
        // Lodging fields
        sleeps: z.string().max(200).optional(),
        address: z.string().max(500).optional(),
        checkInDate: z.string().max(50).optional(),
        checkOutDate: z.string().max(50).optional(),
        checkInTime: z.string().max(20).optional(),
        checkOutTime: z.string().max(20).optional(),
        totalPrice: z.string().max(100).optional(),
        notes: z.string().max(1000).optional(),
        // Transport fields
        transportType: z.string().max(100).optional(),
        pickupLocation: z.string().max(500).optional(),
        pickupTime: z.string().max(50).optional(),
        // Lodging photo URL (og:image fetched in AddPropertySheet).
        imageUrl: z.string().url().max(2048).optional(),
        // Up to 3 lodging photos. image_url is kept in sync with the
        // first element as the cover the LodgingCard renders.
        imageUrls: z.array(z.string().url().max(2048)).max(3).optional(),
        // Ordering
        sortOrder: z.number().int().default(0),
      })
    )
    .use(requireTripRole("Organizer"))
    .mutation(async ({ ctx, input }) => {
      // INSERT with .select() — uuid PK auto-generated by Postgres
      const { data, error } = await ctx.supabase
        .from("logistics_items")
        .insert({
          trip_id: ctx.tripId,
          type: input.type,
          title: input.title,
          link: input.link ?? null,
          sleeps: input.sleeps ?? null,
          address: input.address ?? null,
          check_in_date: input.checkInDate ?? null,
          check_out_date: input.checkOutDate ?? null,
          check_in_time: input.checkInTime ?? null,
          check_out_time: input.checkOutTime ?? null,
          total_price: input.totalPrice ?? null,
          notes: input.notes ?? null,
          transport_type: input.transportType ?? null,
          pickup_location: input.pickupLocation ?? null,
          pickup_time: input.pickupTime ?? null,
          // image_urls is the source of truth; image_url stays in sync
          // with the first element as the cover. Fall back to the
          // legacy single imageUrl when imageUrls isn't provided.
          image_urls: input.imageUrls ?? (input.imageUrl ? [input.imageUrl] : []),
          image_url: input.imageUrls?.[0] ?? input.imageUrl ?? null,
          sort_order: input.sortOrder,
          created_by: ctx.user!.id,
        })
        .select()
        .single();

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: `Failed to create logistics item: ${error.message}`,
        });
      }

      return data;
    }),

  // -----------------------------------------------------------------------
  // update — Organizer+ can edit logistics items
  // -----------------------------------------------------------------------
  update: authedProcedure
    .input(
      z.object({
        tripId: z.string(),
        itemId: z.string(),
        type: logisticsType.optional(),
        title: z.string().min(1).max(200).optional(),
        link: z.string().max(1000).nullable().optional(),
        sleeps: z.string().max(200).nullable().optional(),
        address: z.string().max(500).nullable().optional(),
        checkInDate: z.string().max(50).nullable().optional(),
        checkOutDate: z.string().max(50).nullable().optional(),
        checkInTime: z.string().max(20).nullable().optional(),
        checkOutTime: z.string().max(20).nullable().optional(),
        totalPrice: z.string().max(100).nullable().optional(),
        notes: z.string().max(1000).nullable().optional(),
        transportType: z.string().max(100).nullable().optional(),
        pickupLocation: z.string().max(500).nullable().optional(),
        pickupTime: z.string().max(50).nullable().optional(),
        imageUrl: z.string().url().max(2048).nullable().optional(),
        imageUrls: z.array(z.string().url().max(2048)).max(3).nullable().optional(),
        sortOrder: z.number().int().optional(),
      })
    )
    .use(requireTripRole("Organizer"))
    .mutation(async ({ ctx, input }) => {
      const update: Record<string, unknown> = {};
      if (input.type !== undefined) update.type = input.type;
      if (input.title !== undefined) update.title = input.title;
      if (input.link !== undefined) update.link = input.link;
      if (input.sleeps !== undefined) update.sleeps = input.sleeps;
      if (input.address !== undefined) update.address = input.address;
      if (input.checkInDate !== undefined) update.check_in_date = input.checkInDate;
      if (input.checkOutDate !== undefined) update.check_out_date = input.checkOutDate;
      if (input.checkInTime !== undefined) update.check_in_time = input.checkInTime;
      if (input.checkOutTime !== undefined) update.check_out_time = input.checkOutTime;
      if (input.totalPrice !== undefined) update.total_price = input.totalPrice;
      if (input.notes !== undefined) update.notes = input.notes;
      if (input.transportType !== undefined) update.transport_type = input.transportType;
      if (input.pickupLocation !== undefined) update.pickup_location = input.pickupLocation;
      if (input.pickupTime !== undefined) update.pickup_time = input.pickupTime;
      // imageUrls is the source of truth when provided; keep image_url
      // synced to the cover (first element). When only the legacy
      // imageUrl is sent, update image_url alone.
      if (input.imageUrls !== undefined) {
        const urls = input.imageUrls ?? [];
        update.image_urls = urls;
        update.image_url = urls[0] ?? null;
      } else if (input.imageUrl !== undefined) {
        update.image_url = input.imageUrl;
      }
      if (input.sortOrder !== undefined) update.sort_order = input.sortOrder;

      if (Object.keys(update).length === 0) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "No fields to update" });
      }

      const { data, error } = await ctx.supabase
        .from("logistics_items")
        .update(update)
        .eq("id", input.itemId)
        .eq("trip_id", ctx.tripId)
        .select()
        .single();

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to update logistics item",
        });
      }

      return data;
    }),

  // -----------------------------------------------------------------------
  // confirm / unconfirm — Organizer+ can lock in a lodging property
  // -----------------------------------------------------------------------
  confirm: authedProcedure
    .input(z.object({ tripId: z.string(), itemId: z.string() }))
    .use(requireTripRole("Organizer"))
    .mutation(async ({ ctx, input }) => {
      const { error } = await ctx.supabase
        .from("logistics_items")
        .update({ is_confirmed: true })
        .eq("id", input.itemId)
        .eq("trip_id", ctx.tripId);

      if (error) {
        throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Failed to confirm item" });
      }
      return { success: true };
    }),

  unconfirm: authedProcedure
    .input(z.object({ tripId: z.string(), itemId: z.string() }))
    .use(requireTripRole("Organizer"))
    .mutation(async ({ ctx, input }) => {
      const { error } = await ctx.supabase
        .from("logistics_items")
        .update({ is_confirmed: false })
        .eq("id", input.itemId)
        .eq("trip_id", ctx.tripId);

      if (error) {
        throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Failed to unconfirm item" });
      }
      return { success: true };
    }),

  // -----------------------------------------------------------------------
  // remove — Organizer+ can delete logistics items
  // -----------------------------------------------------------------------
  remove: authedProcedure
    .input(z.object({ tripId: z.string(), itemId: z.string() }))
    .use(requireTripRole("Organizer"))
    .mutation(async ({ ctx, input }) => {
      const { error } = await ctx.supabase
        .from("logistics_items")
        .delete()
        .eq("id", input.itemId)
        .eq("trip_id", ctx.tripId);

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to remove logistics item",
        });
      }

      return { success: true };
    }),
});
