import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { router, authedProcedure } from "../trpc";
import { requireTripMember, requireTripRole } from "../middleware";

const logisticsType = z.enum(["lodging", "transport", "general"]);

export const logisticsRouter = router({
  // -----------------------------------------------------------------------
  // list — any member can view logistics items
  // -----------------------------------------------------------------------
  list: authedProcedure
    .input(z.object({ tripId: z.string() }))
    .use(requireTripMember)
    .query(async ({ ctx }) => {
      const { data, error } = await ctx.supabase
        .from("logistics_items")
        .select("*")
        .eq("trip_id", ctx.tripId)
        .order("sort_order", { ascending: true })
        .order("created_at", { ascending: true });

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to fetch logistics items",
        });
      }

      return data ?? [];
    }),

  // -----------------------------------------------------------------------
  // create — Planner+ can add logistics items (RLS INSERT RETURNING split)
  // -----------------------------------------------------------------------
  create: authedProcedure
    .input(
      z.object({
        tripId: z.string(),
        type: logisticsType,
        label: z.string().min(1).max(200),
        detail: z.string().max(1000).optional(),
        // Lodging fields
        propertyName: z.string().max(200).optional(),
        address: z.string().max(500).optional(),
        checkInTime: z.string().max(50).optional(),
        checkOutTime: z.string().max(50).optional(),
        // Transport fields
        transportType: z.string().max(100).optional(),
        pickupLocation: z.string().max(500).optional(),
        pickupTime: z.string().max(50).optional(),
        // Ordering
        sortOrder: z.number().int().default(0),
      })
    )
    .use(requireTripRole("Planner"))
    .mutation(async ({ ctx, input }) => {
      // INSERT with .select() — uuid PK auto-generated by Postgres
      const { data, error } = await ctx.supabase
        .from("logistics_items")
        .insert({
          trip_id: ctx.tripId,
          type: input.type,
          label: input.label,
          detail: input.detail ?? null,
          property_name: input.propertyName ?? null,
          address: input.address ?? null,
          check_in_time: input.checkInTime ?? null,
          check_out_time: input.checkOutTime ?? null,
          transport_type: input.transportType ?? null,
          pickup_location: input.pickupLocation ?? null,
          pickup_time: input.pickupTime ?? null,
          sort_order: input.sortOrder,
          created_by: ctx.user!.id,
        })
        .select()
        .single();

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: `Failed to create logistics item: ${error.message}`,
        });
      }

      return data;
    }),

  // -----------------------------------------------------------------------
  // update — Planner+ can edit logistics items
  // -----------------------------------------------------------------------
  update: authedProcedure
    .input(
      z.object({
        tripId: z.string(),
        itemId: z.string(),
        type: logisticsType.optional(),
        label: z.string().min(1).max(200).optional(),
        detail: z.string().max(1000).nullable().optional(),
        propertyName: z.string().max(200).nullable().optional(),
        address: z.string().max(500).nullable().optional(),
        checkInTime: z.string().max(50).nullable().optional(),
        checkOutTime: z.string().max(50).nullable().optional(),
        transportType: z.string().max(100).nullable().optional(),
        pickupLocation: z.string().max(500).nullable().optional(),
        pickupTime: z.string().max(50).nullable().optional(),
        sortOrder: z.number().int().optional(),
      })
    )
    .use(requireTripRole("Planner"))
    .mutation(async ({ ctx, input }) => {
      const update: Record<string, unknown> = {};
      if (input.type !== undefined) update.type = input.type;
      if (input.label !== undefined) update.label = input.label;
      if (input.detail !== undefined) update.detail = input.detail;
      if (input.propertyName !== undefined) update.property_name = input.propertyName;
      if (input.address !== undefined) update.address = input.address;
      if (input.checkInTime !== undefined) update.check_in_time = input.checkInTime;
      if (input.checkOutTime !== undefined) update.check_out_time = input.checkOutTime;
      if (input.transportType !== undefined) update.transport_type = input.transportType;
      if (input.pickupLocation !== undefined) update.pickup_location = input.pickupLocation;
      if (input.pickupTime !== undefined) update.pickup_time = input.pickupTime;
      if (input.sortOrder !== undefined) update.sort_order = input.sortOrder;

      if (Object.keys(update).length === 0) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "No fields to update" });
      }

      const { data, error } = await ctx.supabase
        .from("logistics_items")
        .update(update)
        .eq("id", input.itemId)
        .eq("trip_id", ctx.tripId)
        .select()
        .single();

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to update logistics item",
        });
      }

      return data;
    }),

  // -----------------------------------------------------------------------
  // remove — Planner+ can delete logistics items
  // -----------------------------------------------------------------------
  remove: authedProcedure
    .input(z.object({ tripId: z.string(), itemId: z.string() }))
    .use(requireTripRole("Planner"))
    .mutation(async ({ ctx, input }) => {
      const { error } = await ctx.supabase
        .from("logistics_items")
        .delete()
        .eq("id", input.itemId)
        .eq("trip_id", ctx.tripId);

      if (error) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Failed to remove logistics item",
        });
      }

      return { success: true };
    }),
});
